apiVersion: batch/v1
kind: Job
metadata:
  namespace: home
  name: ocis-init
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ocis-init
          image: owncloud/ocis:latest
          command: ["ocis"]
          args: ["init", "--insecure", "yes"]
          volumeMounts:
            - name: config
              mountPath: /etc/ocis
            - name: data
              mountPath: /var/lib/ocis
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: ocis-config
        - name: data
          persistentVolumeClaim:
            claimName: ocis-data
