kind: PersistentVolume
apiVersion: v1
metadata:
  name: kube-ocis-storage-data
  namespace: home
  labels:
    type: local
spec:
  capacity:
    storage: 512Gi
  storageClassName: kube-ocis-storage-data
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/ocis/ocis-data
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kube-ocis-storage-config
  namespace: home
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  storageClassName: ocis-config
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/ocis/ocis-config