apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  interval: 10m
  chart:
    spec:
      chart: trivy-operator
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system
      interval: 1h
  values:
    serviceMonitor:
      enabled: true
    trivy:
      severity: CRITICAL,HIGH,MEDIUM
