apiVersion: v1
kind: ServiceAccount
metadata:
  name: trivy-report-exporter
  namespace: internal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trivy-report-reader
rules:
  - apiGroups: ["aquasecurity.github.io"]
    resources:
      - vulnerabilityreports
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trivy-report-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: trivy-report-reader
subjects:
  - kind: ServiceAccount
    name: trivy-report-exporter
    namespace: internal
