apiVersion: batch/v1
kind: CronJob
metadata:
  name: trivy-report-exporter
  namespace: internal
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: trivy-report-exporter
          restartPolicy: OnFailure
          volumes:
            - name: reports
              persistentVolumeClaim:
                claimName: trivy-reports
          containers:
            - name: exporter
              image: ghcr.io/aquasecurity/trivy:0.50.1
              volumeMounts:
                - name: reports
                  mountPath: /reports
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  kubectl get vulnerabilityreports -A -o json > /tmp/reports.json
                  trivy convert \
                    --format template \
                    --template "@/contrib/html.tpl" \
                    /tmp/reports.json \
                    > /reports/index.html
