apiVersion: batch/v1
kind: CronJob
metadata:
  name: trivy-report-exporter
  namespace: internal
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: trivy-report-exporter
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: trivy-report-exporter
        spec:
          serviceAccountName: trivy-report-exporter
          restartPolicy: OnFailure

          volumes:
            - name: reports
              persistentVolumeClaim:
                claimName: trivy-reports

          containers:
            - name: kubectl-exporter
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  set -e

                  echo "Cleaning up old jobs and pods..."
                  kubectl delete jobs,pods \
                    -n internal \
                    -l app=trivy-report-exporter \
                    --ignore-not-found

                  echo "Exporting vulnerability reports..."
                  kubectl get vulnerabilityreports -A -o json \
                    > /reports/reports.json
              volumeMounts:
                - name: reports
                  mountPath: /reports
