apiVersion: batch/v1
kind: CronJob
metadata:
  name: trivy-report-exporter
  namespace: internal
spec:
  schedule: "*/30 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: trivy-report-exporter
          restartPolicy: OnFailure

          volumes:
            - name: work
              emptyDir: {}
            - name: reports
              persistentVolumeClaim:
                claimName: trivy-reports

          containers:
            - name: kubectl-exporter
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  kubectl get vulnerabilityreports -A -o json > /work/reports.json
              volumeMounts:
                - name: work
                  mountPath: /work

            - name: trivy-converter
              image: sandbox:latest
              command:
                - /bin/sh
                - -c
                - |
                  sleep 99999
              volumeMounts:
                - name: work
                  mountPath: /work
                - name: reports
                  mountPath: /reports
