apiVersion: v1
kind: Pod
metadata:
  name: nfs-test
  namespace: shared
spec:
  containers:
    - name: test
      image: busybox
      command: ["sh", "-c", "sleep 3600000"]
      volumeMounts:
        - mountPath: /mnt/data
          name: shared
  volumes:
    - name: shared
      persistentVolumeClaim:
        claimName: shared-nfs-pvc
