apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-nfs-pvc
  namespace: shared
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: shared-nfs-pv
