apiVersion: v1
kind: Pod
metadata:
  name: busybox-nfs
  namespace: internal
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 3600"]
      volumeMounts:
        - name: nfs-storage
          mountPath: /mnt/data
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: nfs-pvc
