---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncloud-files-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /data/owncloud-files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-files
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncloud-mysql-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /data/owncloud-mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-mysql
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: owncloud-redis-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /data/owncloud-redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-redis
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
