---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owncloud-secrets
                  key: db-root-password
            - name: MYSQL_USER
              value: owncloud
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: owncloud-secrets
                  key: db-password
            - name: MYSQL_DATABASE
              value: owncloud
            - name: MARIADB_AUTO_UPGRADE
              value: "1"
          command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-u", "root", "--password=owncloud"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-u", "root", "--password=owncloud"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: owncloud-mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: home
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
