---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6
          command: ["--databases", "1"]
          volumeMounts:
            - name: redis-data
              mountPath: /data
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: owncloud-redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: home
spec:
  ports:
    - port: 6379
  selector:
    app: redis
