apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: weave-gitops-source
  namespace: flux-system
spec:
  interval: 1h
  url: https://github.com/weaveworks/weave-gitops
  ref:
    tag: v0.32.0   # or "latest" tag you prefer
